name: guardianlens_app
description: "GuardianLens Parent Dashboard for monitoring children's YouTube subscriptions."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Routing
  go_router: ^13.2.0
  
  # Network & API
  dio: ^5.4.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  tutorial_coach_mark: ^1.2.11
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.5
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  bloc_test: ^9.1.6
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
