# This file configures the analyzer to use the lint rule set from `package:flutter_lints`
# and defines customizations for stricter linting rules.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Error rules
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    no_duplicate_case_values: true
    unrelated_type_equality_checks: true
    valid_regexps: true

    # Style rules
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_multiple_declarations_per_line: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: true
    prefer_single_quotes: true
    sort_child_properties_last: true

    # Flutter rules
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true

    # Additional rules
    avoid_print: true
    prefer_relative_imports: true
    avoid_void_async: true
    no_logic_in_create_state: true
    prefer_void_to_null: true